site_name: Velocity Case Tracker Documentation
site_url: http://www.mkdocs.org
site_description: Project documentation with Markdown.
site_author: Tom Christie & Dougal Matthews

repo_url: https://github.com/mkdocs/mkdocs/

pages:
- Home: index.md
- About: about/about.md

markdown_extensions:
    - toc:
        permalink: 
    - admonition:

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, <a href="http://www.dougalmatthews.com/">Dougal Matthews</a>.
google_analytics: ['UA-27795084-5', 'mkdocs.org']

theme: readthedocs
